name: Build Test
on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-test:
    name: runner / Build Test actions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - run: yarn install

      - name: Build
        run: yarn build
